Navigation
anandsr21harshit/Edith pull request #10
Opened 2022-02-08 17:44 UTC by anandsr21harshit

Navigation bar added

2022-02-09 04:46 UTC, OmKakatkar requested changes

2022-02-09 04:46 UTC, OmKakatkar commented on Components/Navigation/navigation.css
> +    background-color: tomato;
Try to use variables for colors, they help if you need to change the color later on

2022-02-09 04:46 UTC, OmKakatkar commented on Components/Navigation/navigation.css
> +    color: white;
CSS variables for color

2022-02-09 13:13 UTC, anandsr21harshit commented on Components/Navigation/navigation.css
> +    background-color: tomato;
Done

2022-02-09 13:13 UTC, anandsr21harshit commented on Components/Navigation/navigation.css
> +    color: white;
Done

2022-02-09 13:15 UTC, OmKakatkar approved these changes

2022-02-10 16:44 UTC, romabulani approved these changes
Good to merge

2022-02-10 17:41 UTC, merged