Buttons
anandsr21harshit/Edith pull request #3
Opened 2022-01-29 17:52 UTC by anandsr21harshit

Three types of buttons

1. Simple buttons
2. Outline buttons
3. Disabled buttons

2022-01-29 18:29 UTC, Parul1999 commented on Components/Buttons/Buttons.css
> +    border: 2px solid black;
Use same units , e.g border-radius is in rem but border is in px . Consistency is needed.

2022-01-29 18:30 UTC, Parul1999 requested changes
Use the same units in CSS, as mentioned in the comment.

2022-01-30 04:36 UTC, OmKakatkar approved these changes
Looks good to merge, a suggestion would be to explore on the disabled attribute of the button element.

2022-01-30 09:01 UTC, anandsr21harshit commented
Units changed

2022-01-30 12:03 UTC, scjuly19 approved these changes

2022-01-30 14:03 UTC, merged