Feat: rounded and responsive image added
anandsr21harshit/Edith pull request #6
Opened 2022-02-02 14:09 UTC by anandsr21harshit

2022-02-02 15:56 UTC, varnita619 approved these changes
Everything seems good

2022-02-05 09:14 UTC, ddivyansh18 requested changes

2022-02-05 09:14 UTC, ddivyansh18 commented on Components/Image/image.html
> +    </div>
Add text to alt content of images

2022-02-05 09:53 UTC, manish591 reviewed
Looking good. Once you have added alt then ping me. I'll approve these changes.

2022-02-06 10:17 UTC, anandsr21harshit commented on Components/Image/image.html
> +    </div>
Updated

2022-02-06 10:56 UTC, manish591 approved these changes
Good to merge

2022-02-06 14:30 UTC, merged